<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_Debug is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://firegento.com). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>
<?php
/**
 * @var $this FireGento_Debug_Block_Diagnostic_CheckSystem
 */
?>
<div id="page:main-container">
	<div class="content-header">
		<table cellspacing="0">
			<tr>
				<td style="width:50%;"><h3><?php echo $this->__('Check System'); ?></h3></td>
				<td class="form-buttons"></td>
			</tr>
		</table>
	</div>

    <div class="col2-set">
        <div class="col1">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Magento Info') ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="label"><label><?php echo $this->__('Edition:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMagento()->getEdition()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Version:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMagento()->getVersion()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Developer Mode:')?></label></td>
                                <td class="value"><?php echo $this->renderBooleanField($this->getSystem()->getMagento()->getDeveloperMode()) ?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Add Secret Key to URLs:')?></label></td>
                                <td class="value"><?php echo $this->renderBooleanField($this->getSystem()->getMagento()->getSecretKey())?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Use Flat Catalog Category:')?></label></td>
                                <td class="value"><?php echo $this->renderBooleanField($this->getSystem()->getMagento()->getFlatCatalogCategory())?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Use Flat Catalog Product:')?></label></td>
                                <td class="value"><?php echo $this->renderBooleanField($this->getSystem()->getMagento()->getFlatCatalogProduct())?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Cache status:')?></label></td>
                                <td class="value">
                                    <?php echo $this->getSystem()->getMagento()->getCacheStatus()?><br />
                                    <a href="<?php echo $this->getUrl('adminhtml/cache/') ?>">&raquo; <?php echo $this->__('Cache Management')?></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Index status:')?></label></td>
                                <td class="value">
                                    <?php echo $this->getSystem()->getMagento()->getIndexStatus()?><br />
                                    <a href="<?php echo $this->getUrl('adminhtml/process/list')?>">&raquo; <?php echo $this->__('Index Management')?></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('PHP Info') ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="label"><label><?php echo $this->__('Version:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getPhp()->getVersion()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Server API:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getPhp()->getServerApi()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Memory Limit:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getPhp()->getMemoryLimit()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Max. Execution Time:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getPhp()->getMaxExecutionTime()?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('MySQL Info') ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="label"><label><?php echo $this->__('Version:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getVersion()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Server API:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getServerApi()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Database Name:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getDatabaseName()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Database Tables:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getDatabaseTables()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Database Table Prefix:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getTablePrefix()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Connection Timeout:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getConnectionTimeout()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Wait Timeout:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getMysql()->getWaitTimeout()?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col2">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Server Info') ?></h4>
                </div>

                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="label"><label><?php echo $this->__('Info:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getServer()->getInfo()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Domain:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getServer()->getDomain()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Server IP:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getServer()->getIp()?></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Server Directory:')?></label></td>
                                <td class="value"><?php echo $this->getSystem()->getServer()->getDir()?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('System Requirements') ?></h4>
                </div>

                <?php $requirements = $this->getSystem()->getRequirements()->getData(); ?>
                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list firegento-settings-table" cellspacing="0" cellpadding="0">
                            <thead>
                                <tr>
                                    <th class="label col1"><?php echo $this->__('Requirement')?></th>
                                    <th class="value col2"><?php echo $this->__('Recommended Value')?></th>
                                    <th class="value col3"><?php echo $this->__('Current Value')?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($requirements as $requirement): ?>
                                <tr>
                                    <td class="label col1"><label><?php echo $this->__($requirement['label'])?></label></td>
                                    <td class="value col2"><?php echo $requirement['recommended_value']?></td>
                                    <td class="value col3 <?php echo $this->renderRequirementValue($requirement['result']) ?>">
                                        <?php echo $requirement['current_value']?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
