<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_Debug is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://firegento.com). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>
<div id="page:main-container">
	<div class="content-header">
		<table cellspacing="0">
			<tr>
				<td style="width:50%;"><h3><?php echo $this->__('phpinfo()'); ?></h3></td>
				<td class="form-buttons"></td>
			</tr>
		</table>
	</div>
	<?php echo $this->getPhpInfo()?>
</div>
